name: Bookstore CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json
          admin/package-lock.json

    # Frontend
    - name: Frontend - Install & Build
      working-directory: ./frontend
      run: |
        npm install
        npm run lint
        npm run build

    # Admin
    - name: Admin - Install & Build
      working-directory: ./admin
      run: |
        npm install
        npm run lint
        npm run build

    # Backend
    - name: Backend - Install & Lint
      working-directory: ./backend
      run: |
        npm install
        npm run lint
